# Generated by Django 5.0.7 on 2025-09-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_likes_count_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biometric_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
