# Generated by Django 5.0.7 on 2025-09-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_biometric_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biometric_action',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='biometric_challenge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
